upstream portainer_upstream {
    server ktb-portainer:9000;
}

server {
    listen 80;
    server_name ktb-nginx;

    location /portainer {
        return 301 /portainer/;
    }

    location /portainer/ {
        set $upstream_endpoint http://portainer_upstream;
        rewrite ^/portainer/(.*) /$1 break;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_pass $upstream_endpoint;
    }

    location /portainer/api/websocket/ {
        set $upstream_endpoint http://portainer_upstream/api/websocket;
        rewrite ^/portainer/api/websocket/(.*) /$1 break;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_http_version 1.1;
        proxy_pass $upstream_endpoint;
    }
}