version: '3.8'

services:
  ktb-certbot:
    image: certbot/certbot
    container_name: ktb-certbot
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
  
  ktb-nginx:
    build: ./ktb-nginx
    container_name: ktb-nginx
    restart: unless-stopped
    networks:
      - ktb-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ktb-nginx/conf.d:/etc/nginx/conf.d
      - ./ktb-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_html:/usr/share/nginx/html
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot

  ktb-portainer:
    build: ./ktb-portainer
    container_name: ktb-portainer
    restart: unless-stopped
    networks:
      - ktb-network
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
  certbot_conf:
  certbot_www:
  nginx_html:

networks:
  ktb-network:
    driver: bridge