FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf
COPY conf.d/*.conf /etc/nginx/conf.d/
COPY ./etc/letsencrypt/certbot/conf /etc/letsencrypt
COPY ./etc/letsencrypt/certbot/www /var/www/certbot

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
